logging:
  level:
    blog: WARN
    org: WARN
    org.hibernate.SQL: DEBUG


spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${JDBC_DATABASE_URL:}
    username: ${JDBC_DATABASE_USERNAME:}
    password: ${JDBC_DATABASE_PASSWORD:}
  jpa:
    hibernate:
      ddl-auto: create
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  mvc:
    hiddenmethod:
      filter:
        enabled: true
    throw-exception-if-no-handler-found: true
    static-path-pattern: /static/**
    resources:
      static-locations: "classpath:/static/"
server:
  port : ${PORT:8080}
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB
      enabled: true




cloudinary:
  cloud-name: dzjgi2c7y
  api-key: 459312976342331
  api-secret: ${CLOUDINARY_SECRET}